apiVersion: v1
kind: Service
metadata:
  name: calcom-api-service
spec:
  selector:
    app: calcom-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Should match containerPort in deployment
  type: LoadBalancer  # Use LoadBalancer if you want to expose externally
